name: Generator
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.1
        with:
          node-version: 12
      - name: Generate list
        run: |
          npm install
          npm run gen:list
          git config --local user.email "trustbot@trustwallet.com"
          git config --local user.name "Trust Wallet Actions Bot"
          git commit -m "Generate whitelist and blacklist" -a
          git remote set-url origin https://x-access-token:${DANGER_GITHUB_API_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Generate list"; git push origin ${GITHUB_REF})
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}